### ISSUE TITLE
Make Phoenix dependency optional

### ISSUE THREAD

**Issue by wojtekmach** [mfeckie/ex_brotli#3]
Thanks for creating this library! Consider making the phoenix dependency optional (and guarding the digester implementation with an `if Code.ensure_loaded?`) so that when people just need brotli they don't need to bring in Phoenix and all its dependencies.

**Comment by wojtekmach** [comment]
Looks good to me, thanks!

**Comment by mfeckie** [comment]
Published https://hex.pm/packages/ex_brotli/0.4.0

Let me know if there's anything else that would be helpful 😄
